"""make ss val nullable

Revision ID: 0a74397f6035
Revises: 940eb8decc9f
Create Date: 2019-04-28 20:38:29.854518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a74397f6035'
down_revision = '940eb8decc9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SS', 'val',
               existing_type=mysql.VARCHAR(length=8192),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SS', 'val',
               existing_type=mysql.VARCHAR(length=8192),
               nullable=False)
    # ### end Alembic commands ###
