"""add exp to profile db

Revision ID: 1502b49254e3
Revises: 91c3e581d794
Create Date: 2019-05-06 19:48:46.502072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1502b49254e3'
down_revision = '91c3e581d794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Profile', sa.Column('exp', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Profile', 'exp')
    # ### end Alembic commands ###
