"""add capture, arrival, and finished time as double

Revision ID: 20cb81370e33
Revises: c9f2605bd382
Create Date: 2019-03-18 18:13:48.817069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20cb81370e33'
down_revision = 'c9f2605bd382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LegoLatency', sa.Column('arrival', sa.FLOAT(precision=53), nullable=True))
    op.add_column('LegoLatency', sa.Column('capture', sa.FLOAT(precision=53), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LegoLatency', 'capture')
    op.drop_column('LegoLatency', 'arrival')
    # ### end Alembic commands ###
