"""update datastat

Revision ID: 302b491278ce
Revises: 712b1042ea3c
Create Date: 2019-05-13 16:14:27.713512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302b491278ce'
down_revision = '712b1042ea3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
