"""Added basic tables2

Revision ID: 8c0c0ed1d004
Revises: d90d117fe45c
Create Date: 2019-03-07 18:12:07.931413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0c0ed1d004'
down_revision = 'd90d117fe45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Exp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('val', sa.String(length=512), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ExpLatency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('val', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LegoLatency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('val', sa.String(length=512), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LegoLatency')
    op.drop_table('ExpLatency')
    op.drop_table('Exp')
    # ### end Alembic commands ###
