"""add height width

Revision ID: 8e09ba3222b3
Revises: 1803db7440fa
Create Date: 2019-05-31 09:06:29.661877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e09ba3222b3'
down_revision = '1803db7440fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Trace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('trace', sa.String(length=512), nullable=False),
    sa.Column('fid', sa.String(length=32), nullable=False),
    sa.Column('symbolic_state', sa.String(length=60000), nullable=True),
    sa.Column('rot_x', sa.FLOAT(precision=53), nullable=True),
    sa.Column('rot_y', sa.FLOAT(precision=53), nullable=True),
    sa.Column('rot_z', sa.FLOAT(precision=53), nullable=True),
    sa.Column('acc_x', sa.FLOAT(precision=53), nullable=True),
    sa.Column('acc_y', sa.FLOAT(precision=53), nullable=True),
    sa.Column('acc_z', sa.FLOAT(precision=53), nullable=True),
    sa.Column('sensor_timestamp', sa.DateTime(), nullable=True),
    sa.Column('active', sa.String(length=32), nullable=True),
    sa.Column('instruction', sa.String(length=16384), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Sec6IntraAppBk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sec6IntraAppBk',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('app', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('client', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('arrival', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('finished', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('reply', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('utility', mysql.FLOAT(), nullable=True),
    sa.Column('result', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('is_gt_active', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('Trace')
    # ### end Alembic commands ###
