"""add index to SS table

Revision ID: 8fe434c4a08d
Revises: a313d5ae97b9
Create Date: 2019-04-07 16:47:26.663273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe434c4a08d'
down_revision = 'a313d5ae97b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SS', sa.Column('index', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SS', 'index')
    # ### end Alembic commands ###
