"""Added account table

Revision ID: 9a492d981162
Revises: a69472dd044e
Create Date: 2019-03-08 18:28:40.828888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a492d981162'
down_revision = 'a69472dd044e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LegoLatency', sa.Column('index', sa.Integer(), nullable=True))
    op.add_column('LegoLatency', sa.Column('name', sa.String(length=512), nullable=False))
    op.drop_column('LegoLatency', 'key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LegoLatency', sa.Column('key', mysql.VARCHAR(length=512), nullable=False))
    op.drop_column('LegoLatency', 'name')
    op.drop_column('LegoLatency', 'index')
    # ### end Alembic commands ###
