"""add in symbolic state table

Revision ID: a313d5ae97b9
Revises: 20cb81370e33
Create Date: 2019-04-04 17:36:21.418457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a313d5ae97b9'
down_revision = '20cb81370e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('val', sa.String(length=8192), nullable=False),
    sa.Column('trace', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SS')
    # ### end Alembic commands ###
