"""add exp name and num_worker for resourcelatency

Revision ID: a4fa2661cc05
Revises: df219b111a5d
Create Date: 2019-05-15 22:40:57.931981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4fa2661cc05'
down_revision = 'df219b111a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ResourceLatency', sa.Column('name', sa.String(length=512), nullable=True))
    op.add_column('ResourceLatency', sa.Column('num_worker', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ResourceLatency', 'num_worker')
    op.drop_column('ResourceLatency', 'name')
    # ### end Alembic commands ###
