"""changed profile cpu latency to float

Revision ID: a60406f13b95
Revises: 1502b49254e3
Create Date: 2019-05-12 13:59:06.002967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60406f13b95'
down_revision = '1502b49254e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
