"""add in gtinst2

Revision ID: a6c969ef516a
Revises: ef3c4b94c845
Create Date: 2019-05-23 19:46:08.995484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c969ef516a'
down_revision = 'ef3c4b94c845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GTInst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app', sa.String(length=512), nullable=False),
    sa.Column('trace', sa.String(length=512), nullable=False),
    sa.Column('value', sa.String(length=65535), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GTInst')
    # ### end Alembic commands ###
