"""changed cpu and mem to float 53

Revision ID: b1b34d862ddd
Revises: a60406f13b95
Create Date: 2019-05-12 14:03:50.820874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b34d862ddd'
down_revision = 'a60406f13b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
