"""changed sec6 column name

Revision ID: b6abe28f794b
Revises: 84234e01c344
Create Date: 2019-05-22 10:48:58.342864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6abe28f794b'
down_revision = '84234e01c344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sec6IntraApp', sa.Column('is_gt_active', sa.Integer(), nullable=True))
    op.drop_column('Sec6IntraApp', 'processed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sec6IntraApp', sa.Column('processed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('Sec6IntraApp', 'is_gt_active')
    # ### end Alembic commands ###
