"""add height width to trace

Revision ID: c5892dd534d8
Revises: 1a021f1c5022
Create Date: 2019-05-31 09:10:40.166705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5892dd534d8'
down_revision = '1a021f1c5022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Trace',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=512), nullable=False),
                    sa.Column('trace', sa.String(length=512), nullable=False),
                    sa.Column('fid', sa.String(length=32), nullable=False),
                    sa.Column('symbolic_state', sa.Text(), nullable=True),
                    sa.Column('rot_x', sa.FLOAT(precision=53), nullable=True),
                    sa.Column('rot_y', sa.FLOAT(precision=53), nullable=True),
                    sa.Column('rot_z', sa.FLOAT(precision=53), nullable=True),
                    sa.Column('acc_x', sa.FLOAT(precision=53), nullable=True),
                    sa.Column('acc_y', sa.FLOAT(precision=53), nullable=True),
                    sa.Column('acc_z', sa.FLOAT(precision=53), nullable=True),
                    sa.Column('sensor_timestamp',
                              sa.DateTime(), nullable=True),
                    sa.Column('active', sa.String(length=32), nullable=True),
                    sa.Column('instruction', sa.Text(), nullable=True),
                    sa.Column('height', sa.Integer(), nullable=True),
                    sa.Column('width', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Trace')
    # ### end Alembic commands ###
