"""float 53

Revision ID: c9f2605bd382
Revises: dd95bb244c71
Create Date: 2019-03-18 18:12:46.016472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f2605bd382'
down_revision = 'dd95bb244c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LegoLatency', sa.Column('finished', sa.FLOAT(precision=53), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LegoLatency', 'finished')
    # ### end Alembic commands ###
