"""Added account table

Revision ID: d8e93dece077
Revises: 9a492d981162
Create Date: 2019-03-08 19:03:45.733186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e93dece077'
down_revision = '9a492d981162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
