"""float 53

Revision ID: dd95bb244c71
Revises: ff24e2c7d03a
Create Date: 2019-03-18 18:12:12.098426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd95bb244c71'
down_revision = 'ff24e2c7d03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
