"""fixed float

Revision ID: ec3c5f73181c
Revises: d8e93dece077
Create Date: 2019-03-18 16:08:34.943685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3c5f73181c'
down_revision = 'd8e93dece077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LegoLatency', sa.Column(
        'arrival', sa.FLOAT(precision='64,16'), nullable=True))
    op.add_column('LegoLatency', sa.Column(
        'capture', sa.FLOAT(precision='64,16'), nullable=True))
    op.add_column('LegoLatency', sa.Column(
        'finished', sa.FLOAT(precision='64,16'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LegoLatency', 'finished')
    op.drop_column('LegoLatency', 'capture')
    op.drop_column('LegoLatency', 'arrival')
    # ### end Alembic commands ###
