"""add in gtinst

Revision ID: ef3c4b94c845
Revises: b6abe28f794b
Create Date: 2019-05-23 19:35:40.272697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3c4b94c845'
down_revision = 'b6abe28f794b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GTInst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app', sa.String(length=512), nullable=False),
    sa.Column('trace', sa.String(length=512), nullable=False),
    sa.Column('value', sa.String(length=1000000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GTInst')
    # ### end Alembic commands ###
