"""add trace table

Revision ID: f361eec28fab
Revises: 1a021f1c5022
Create Date: 2019-05-30 17:24:13.480838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f361eec28fab'
down_revision = '1a021f1c5022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Trace',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=512), nullable=False),
                    sa.Column('trace', sa.String(length=512), nullable=False),
                    sa.Column('fid',  sa.Integer(), nullable=False),
                    sa.Column('symbolic_state', sa.String(
                        length=16000000), nullable=True),
                    sa.Column('rot_x', sa.FLOAT(precision=53), nullable=True),
                    sa.Column('rot_y', sa.FLOAT(precision=53), nullable=True),
                    sa.Column('rot_z', sa.FLOAT(precision=53), nullable=True),
                    sa.Column('acc_x', sa.FLOAT(precision=53), nullable=True),
                    sa.Column('acc_y', sa.FLOAT(precision=53), nullable=True),
                    sa.Column('acc_z', sa.FLOAT(precision=53), nullable=True),
                    sa.Column('sensor_timestamp',
                              sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('Trace')
    # ### end Alembic commands ###
