"""drop float

Revision ID: ff24e2c7d03a
Revises: ec3c5f73181c
Create Date: 2019-03-18 18:11:59.161891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff24e2c7d03a'
down_revision = 'ec3c5f73181c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LegoLatency', 'arrival')
    op.drop_column('LegoLatency', 'capture')
    op.drop_column('LegoLatency', 'finished')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LegoLatency', sa.Column('finished', mysql.FLOAT(precision=64, scale=16), nullable=True))
    op.add_column('LegoLatency', sa.Column('capture', mysql.FLOAT(precision=64, scale=16), nullable=True))
    op.add_column('LegoLatency', sa.Column('arrival', mysql.FLOAT(precision=64, scale=16), nullable=True))
    # ### end Alembic commands ###
