version: "3.2"
volumes:
  res_prometheus_data:
    external: true
  res_grafana_data:
    external: true
  res_mysql_data:
    external: true
services:
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml:ro
      - res_prometheus_data:/prometheus
    depends_on:
      - cadvisor
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - res_grafana_data:/var/lib/grafana
    env_file:
      - ./grafana.env
  db:
    image: mysql:5.7
    container_name: res-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 13306:3306
    volumes:
      - res_mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: exp
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  db-adminer:
    image: adminer
    container_name: res-db-adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080
