version: "3.2"
volumes:
  res_mysql_data:
    external: true
  res_mysql_phpmyadmin:
services:
  db:
    image: mysql:5.7
    container_name: res-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 13306:3306
    volumes:
      - res_mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: exp
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  db-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: res-db-phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
    volumes:
      - res_mysql_phpmyadmin:/sessions
      - ./phpmyadmin-config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      - db
  # db-adminer:
  #   image: adminer
  #   container_name: res-db-adminer
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 8081:8080
